artikel/urls.py
from django.urls import path
from artikel.views import artikel_by_id_json, show_artikel
from artikel.views import create_new_artikel
from artikel.views import artikel_json
from artikel.views import delete_artikel
from artikel.views import comment_json
from artikel.views import handle_vote, share_exp
from artikel.views import hapus_artikel

app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name="show_artikel"),
    path('create-new-artikel/', create_new_artikel, name="create_new_artikel"),
    path('json/', artikel_json, name='artikel_json'),
    path('comment/json/', comment_json, name='comment_json'),
    path('delete-artikel/<int:id>/', delete_artikel, name="delete-artikel"),
    path('json/<int:id>', artikel_by_id_json, name='artikel_by_id_json'),
    path('<int:id>/vote/<str:action>',handle_vote,name="handle_vote"),
    path('share-exp/', share_exp, name="share-exp"),
    path('hapus-artikel/<int:id>/', hapus_artikel, name="hapus-artikel"),
]

forum/urls.py
from django.urls import path
from forum.views import add_forum, delete_comment, delete_forum, get_forums_json, handle_vote, show_forum_index, show_forum_detail,get_forum_by_pk, add_comment, delete_forum_flutter, add_comment_flutter, delete_comment_flutter, handle_vote_flutter


app_name = 'forum'

urlpatterns = [
    path('',show_forum_index, name="show_forum_index"),
    path('json',get_forums_json, name="get_forums_json"),
    path('json/<int:pk>',get_forum_by_pk, name="get_forum_by_pk"),
    path('add', add_forum, name='add_forum'),
    path('delete/<int:id>',delete_forum,name='delete_forum'),
    path('delete-forum/<int:id>/<str:current_username>',delete_forum_flutter,name='delete_forum_flutter'),
    path('<int:pk>',show_forum_detail, name="show_forum_detail"),
    path('<int:pk>/add-comment',add_comment, name="add_comment"),
    path('<int:pk>/add-comment-flutter/<str:username>',add_comment_flutter, name="add_comment_flutter"),
    path('<int:pk>/delete-comment/<str:username>',delete_comment_flutter,name='delete_comment_flutter'),
    path('<int:pk>/delete-comment/',delete_comment, name="delete_comment"),
    path('<int:pk>/vote/<str:action>',handle_vote,name="handle_vote"),
    path('<int:pk>/vote-flutter/<str:action>',handle_vote_flutter,name="handle_vote")
]

main/urls.py
from django.urls import path
from main.views import  show_landing, register_user, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_landing, name='show_landing'),
    path('login', login_user, name='login' ),
    path('register', register_user, name='register'),
    path('logout', logout_user, name='logout')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('artikel/', include('artikel.urls')),
    path('bmicalculator/', include('bmicalculator.urls')),
    path('report-progress/', include('report.urls')),
    path('forum/', include('forum.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('authentication/',include('authentication.urls'))
]

# TODO: Implement Routings Here

rekomendasi/urls.py
from django.urls import path
from .views import show_rekomendasi, add_rekomendasi, show_json
app_name = 'rekomendasi'

urlpatterns = [
    path('', show_rekomendasi, name='show_rekomendasi'),
    path('add/', add_rekomendasi, name='add_rekomendasi'),
    path('json/', show_json, name='show_json'),
    # path('delete/<str:id>/', delete_rekomendasi, name='delete_rekomendasi'),
]

report/urls.py
from django.urls import path
from report.views import *

app_name = 'report'

urlpatterns = [
    path('', show_reports, name='show_reports'),
    path('json/', show_json, name='show_json'),
    path('json/<str:username>/',show_json_by_username, name="show_json_by_username"),
    path('add-report/', add_report, name='add_report'),
    path('add-report-flutter/', add_report_flutter, name='add_report_flutter'),
    path('delete-report/<int:id>/', delete_report, name='delete_report'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="{% static 'img/heart.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
    rel="stylesheet" />
  <script>
    tailwind.config = {
      important: true,
      theme: {
        extend: {
          animation: {
            "slide-in-fwd-center": "slide-in-fwd-center 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940)   both",
            "slide-out-blurred-right": "slide-out-blurred-right 0.45s cubic-bezier(0.895, 0.030, 0.685, 0.220)   both"
          },
          keyframes: {
            "slide-in-fwd-center": {
              "0%": {
                transform: "translateZ(-1400px)",
                opacity: "0"
              },
              to: {
                transform: "translateZ(0)",
                opacity: "1"
              }
            },
            "slide-out-blurred-right": {
              "0%": {
                transform: "translateX(0) scaleY(1) scaleX(1)",
                "transform-origin": "50% 50%",
                filter: "blur(0)",
                opacity: "1"
              },
              to: {
                transform: "translateX(1000px) scaleX(2) scaleY(.2)",
                "transform-origin": "0% 50%",
                filter: "blur(40px)",
                opacity: "0"
              }
            }
          },
          colors: {
            clifford: '#da373d',
          },
        },
      },
    }
  </script>
  {% block meta %} {% endblock meta %}
</head>

<body class="flex flex-col min-h-screen">
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock navbar %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  {% block content %} {% endblock content %}

  {% include 'footer.html' %}

</body>

</html>

templates/footer.html
<footer class="mt-auto pt-10 w-full h-20 md:h-36">
  <div class="mt-2 text-center font-bold text-red-500">
    © 2022 Kembangin ❤️
  </div>
  <a href="https://github.com/pbp-fasilkom-c02/kembangin">
    <div class="flex justify-center fill-red-500 mt-2">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path
          d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
      </svg>
    </div>
  </a>
</footer>

templates/navbar.html
<script>
  $(document).ready(function () {
    const hamburgerIcon = `<svg id="hamburgerIcon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
</svg>`;
    const xIcon = `<svg id="xIcon" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
</svg>
`;
    $("#toggle-button").click(function () {
      if ($("#navbar-default").hasClass("hidden")) {
        $("#navbar-default").removeClass("hidden");
        $("#hamburgerIcon").remove();
        $("#toggle-button").append(xIcon);
      } else {
        $("#navbar-default").addClass("hidden");
        $("#toggle-button").append(hamburgerIcon);
        $("#xIcon").remove();
      }
    });
  });
</script>
<nav
  class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 md:py-0 shadow-lg z-20"
>
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <a href="/" class="flex items-center">
      <span class="self-center text-xl font-semibold whitespace-nowrap">
        Kembangin ❤️
      </span>
    </a>
    <button
      data-collapse-toggle="navbar-default"
      id="toggle-button"
      type="button"
      class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-gray-200"
      aria-controls="navbar-default"
      aria-expanded="false"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="w-6 h-6"
        id="hamburgerIcon"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
        />
      </svg>
    </button>
    <div
      class="hidden w-full absolute top-10 left-0 md:static md:block md:w-auto rounded-xl shadow-xl md:rounded-none md:shadow-transparent"
      id="navbar-default"
    >
      <ul
        class="flex flex-col px-4 pb-4 pt-0 md:pt-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white"
      >
        <li>
          <a
            href="{% url 'artikel:show_artikel' %}"
            class="block py-2 pr-4 pl-3 rounded md:bg-transparent text-gray-700 hover:text-red-400 md:p-2"
          >
            Artikel
          </a>
        </li>
        <li>
          <a
            href="{% url 'forum:show_forum_index' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            Forum
          </a>
        </li>
        <li>
          <a
            href="{% url 'rekomendasi:show_rekomendasi' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            Kebutuhan Anak
          </a>
        </li>
        <li>
          <a
            href="{% url 'report:show_reports' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            Perkembangan Anak
          </a>
        </li>
        <li>
          <a         
            href="{% url 'bmicalculator:show_bmicalculator' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            BMI
          </a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a
            href="{% url 'user_profile:show_profile' user.pk %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            Account
          </a>
        </li>
        <li>
          <a
            href="{% url 'main:logout' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-red-200 md:hover:bg-transparent md:border-0 md:hover:text-red-400 md:p-2"
          >
            Logout
          </a>
        </li>
        {% else %}
        <div class="text-red-400 pl-3 p-2">
          <a href="{% url 'main:login' %}"> Login </a>
        </div>
        <div
          class="bg-red-400 text-white rounded-lg pl-3 md:pl-2 p-2 text-center"
        >
          <a href="{% url 'main:register'%}"> Sign up </a>
        </div>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>