artikel/urls.py
from django.urls import path
from artikel.views import artikel_by_id_json, show_artikel
from artikel.views import create_new_artikel
from artikel.views import artikel_json
from artikel.views import delete_artikel
from artikel.views import comment_json
from artikel.views import handle_vote, share_exp
from artikel.views import hapus_artikel

app_name = 'artikel'

urlpatterns = [
    path('', show_artikel, name="show_artikel"),
    path('create-new-artikel/', create_new_artikel, name="create_new_artikel"),
    path('json/', artikel_json, name='artikel_json'),
    path('comment/json/', comment_json, name='comment_json'),
    path('delete-artikel/<int:id>/', delete_artikel, name="delete-artikel"),
    path('json/<int:id>', artikel_by_id_json, name='artikel_by_id_json'),
    path('<int:id>/vote/<str:action>',handle_vote,name="handle_vote"),
    path('share-exp/', share_exp, name="share-exp"),
    path('hapus-artikel/<int:id>/', hapus_artikel, name="hapus-artikel"),
]

bmicalculator/urls.py
from django.urls import path
from bmicalculator.views import *
app_name = "bmicalculator"
urlpatterns = [
    path('', show_bmicalculator, name="show_bmicalculator"),
    path('delete/<int:pk>/', delete_task, name="delete"),
    path('add/', add_calculate_ajax, name='add_calculate'),
    path('json/', show_json, name='show_json'),
    path('add_calculate_flutter/', add_calculate_flutter, name='add_calculate_flutter'),
    path('delete_flutter/<int:pk>/', delete_task_flutter, name="delete_flutter"),
]

main/urls.py
from django.urls import path
from main.views import  show_landing, register_user, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_landing, name='show_landing'),
    path('login', login_user, name='login' ),
    path('register', register_user, name='register'),
    path('logout', logout_user, name='logout')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user_profile/', include('user_profile.urls')),
    path('artikel/', include('artikel.urls')),
    path('bmicalculator/', include('bmicalculator.urls')),
    path('report-progress/', include('report.urls')),
    path('forum/', include('forum.urls')),
    path('rekomendasi/', include('rekomendasi.urls')),
    path('authentication/',include('authentication.urls'))
]

# TODO: Implement Routings Here

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_doctor = models.BooleanField(default=False)

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .models import User
from user_profile.models import UserProfile, DoctorProfile
from django.contrib import messages
from artikel.models import Artikel
import operator
from django.views.decorators.csrf import csrf_exempt

def show_landing(request):
    artikel = {}
    top_3 = []
    data = Artikel.objects.all()

    if (len(data) != 0):
        for i in range(0, len(data)):
            artikel[data[i]] = data[i].upvote
        
        sorted_d = dict( sorted(artikel.items(), key=operator.itemgetter(1),reverse=True))
        
        i = 1
        if (len(sorted_d) < 3):
            for key, value in sorted_d.items():
                top_3.append(key)
                     
        else:
            for key, value in sorted_d.items():
                if (i == 4):
                    break
                else:
                    top_3.append(key)
                    i += 1
                    
    context = {
        "data" : top_3
    }

    return render(request,"main.html", context)

def login_user(request):
    if (request.method == "POST"):
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:show_landing')
        messages.info(request, "Wrong username or password!")
    return render(request, "login.html")

@csrf_exempt
def register_user(request):
    if (request.method == "POST"):
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        repeat_password = request.POST.get("repeat_password")
        if (User.objects.filter(username=username) or User.objects.filter(email=email)):
            messages.info(request, "Username or email already taken!")
        elif (password == repeat_password):
            user = User.objects.create_user(username=username, email=email, password=password)
            user_profile = UserProfile.objects.create(user=user)
            if (request.POST.get("doctor_choice") == "yes"):
                user.is_doctor = True
                doctor_profile = DoctorProfile.objects.create(profile = user_profile)
                doctor_profile.save()
            user.save()
            user_profile.save()
            return redirect("main:login")
        else:
            messages.info(request, "Password and repeat password is different!")
    return render(request, "register.html")

def logout_user(request):
    logout(request)
    return redirect("main:login")

main/templates/login.html
{% extends "base.html" %}

{% block meta %}
<title>Kembangin | Login</title>
{% endblock meta %}

{% block content %}
<div class="text-center font-bold flex h-screen" id="content">
    <form method="POST" action="" id="login-form"
        class="grid grid-cols-1 gap-5 bg-red-200 rounded border-4 border-neutral-500 p-5 m-auto">
        {% csrf_token %}
        <div>
            <p class="text-3xl">LOGIN</p>
        </div>
        <div>
            <input type="text" name="username" placeholder="Username"
                class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center">
        </div>
        <div>
            <input type="password" name="password" placeholder="Password"
                class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center">
        </div>
        <div>
            <button
                class="text-lg bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded border-2 border-neutral-500"
                type="submit">Login</button>
        </div>
        {% if messages %}
        <ul class="text-center font-bold text-black-400">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </form>


</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
<title>Kembangin</title>
{% endblock meta %}

{% block content%}

<body class="leading-normal tracking-normal text-white gradient" style="
    font-family: 'Source Sans Pro', sans-serif;
    background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
  ">
  <!--Hero-->
  <div class="pt-14">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      <!--Left Col-->
      <div
        class="flex flex-col w-full lg:ml-24 md:w-2/5 justify-center items-start text-center md:text-left text-white">
        <p class="tracking-widest w-full font-bold">Kembangin</p>
        <h1 class="my-4 text-3xl md:text-4xl lg:text-5xl font-bold leading-tight">
          Solusi Kesehatan Terpercaya
        </h1>
        <p class="leading-normal text-xl md:text-2xl lg:text-2xl mb-8">
          Tanya dokter langsung seputar kesehatan anak, semua bisa di Kembangin!
        </p>
      </div>
      <!--Right Col-->
      <div class="w-3/5 md:w-3/5 lg:w-1/2">
        <img src="https://cdn-icons-png.flaticon.com/512/4807/4807695.png" width="360" height="360"
          style="user-select: auto" class="mx-auto my-10" />
      </div>
    </div>
  </div>
  <div class="relative -mt-12 lg:-mt-24">
    <svg viewBox="0 0 1428 174" version="1.1" xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink">
      <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g transform="translate(-2.000000, 44.000000)" fill="#FFFFFF" fill-rule="nonzero">
          <path
            d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496"
            opacity="0.100000001"></path>
          <path
            d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z"
            opacity="0.100000001"></path>
          <path
            d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z"
            id="Path-4" opacity="0.200000003"></path>
        </g>
        <g transform="translate(-4.000000, 76.000000)" fill="#FFFFFF" fill-rule="nonzero">
          <path
            d="M0.457,34.035 C57.086,53.198 98.208,65.809 123.822,71.865 C181.454,85.495 234.295,90.29 272.033,93.459 C311.355,96.759 396.635,95.801 461.025,91.663 C486.76,90.01 518.727,86.372 556.926,80.752 C595.747,74.596 622.372,70.008 636.799,66.991 C663.913,61.324 712.501,49.503 727.605,46.128 C780.47,34.317 818.839,22.532 856.324,15.904 C922.689,4.169 955.676,2.522 1011.185,0.432 C1060.705,1.477 1097.39,3.129 1121.236,5.387 C1161.703,9.219 1208.621,17.821 1235.4,22.304 C1285.855,30.748 1354.351,47.432 1440.886,72.354 L1441.191,104.352 L1.121,104.031 L0.457,34.035 Z">
          </path>
        </g>
      </g>
    </svg>
  </div>
  <section class="bg-white border-b py-8">
    <div class="container max-w-5xl mx-auto m-8">
      <h2 class="w-full my-2 text-3xl md:text-4xl lg:text-5xl font-bold leading-tight text-center text-gray-800">
        About Us
      </h2>
      <div class="w-full mb-4">
        <div class="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
      </div>
      <div class="flex flex-wrap tracking-wider">
        <div class="text-center lg:text-left sm:w-1/2 my-auto p-6">
          <h3 class="text-2xl md:text-3xl lg:text-3xl text-gray-800 font-bold leading-none mb-3">
            Konsultasi gratis dengan dokter tanpa batas waktu
          </h3>
          <p class="text-gray-600 mb-8">
            Fitur <span class="text-red-500"> forum </span> ini memfasilitasi
            para dokter rekanan Kami sebagai Penyedia Layanan untuk berinteraksi
            dengan Anda melalui diskusi forum yang dapat diakses melalui
            Platform.
            <span class="text-red-500">
              Kami akan berupaya semaksimal mungkin agar dokter rekanan yang
              terdaftar pada Platform dapat memberikan tanggapan atas pertanyaan
              Anda sesegera mungkin.</span>
            Namun demikian, Kami tidak menyarankan Anda menggunakan Platform
            untuk kondisi medis darurat.
          </p>
        </div>
        <div class="w-full sm:w-1/2 p-6 mt-6">
          <img src="https://cdn-icons-png.flaticon.com/512/5996/5996051.png" width="360" height="360"
            style="user-select: auto" />
        </div>
      </div>
      <div class="flex flex-wrap flex-col-reverse sm:flex-row">
        <div class="w-full sm:w-1/2 p-6 mt-6">
          <img src="https://cdn-icons-png.flaticon.com/512/854/854878.png" width="360" height="360"
            style="user-select: auto" />
        </div>
        <div class="text-center lg:text-left sm:w-1/2 my-auto p-6 mt-6">
          <div class="align-middle my-auto">
            <h3 class="text-3xl text-gray-800 font-bold leading-none mb-3">
              Dokter dan orang tua bisa bersama-sama memantau perkembangan anak
            </h3>
            <p class="text-gray-600 mb-8">
              Pemantauan perkembangan anak sangat penting, karena dengan
              pemantauan yang baik dapat dilakukan deteksi dini kelainan pada
              anak. Perkembangan seorang anak normal atau tidak, dapat diketahui
              dengan pemeriksaan dan pemantauan yang berkala dan terus menerus
              oleh tenaga kesehatan
              <br />
              <br />
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="bg-white border-b py-8">
    <div class="container mx-auto flex flex-wrap pt-4 pb-12">
      <h2 class="w-full my-2 text-3xl md:text-4xl lg:text-5xl font-bold leading-tight text-center text-gray-800">
        Artikel
      </h2>
      <div class="w-full mb-4">
        <div class="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
      </div>

      {% for item in data %}
      <div class="w-full md:w-1/3 p-6 flex flex-col flex-grow flex-shrink">
        <div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow">
          <a href="#" class="flex flex-wrap no-underline hover:no-underline">
            <div class="w-full font-bold text-xl text-gray-800 px-6">
              {{ item.title }}
            </div>
            <p class="text-gray-800 text-base px-6 mb-5">
              {{ item.description }}
            </p>
          </a>
        </div>
        <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
          <div class="flex items-center justify-center">
            <a href="{% url 'artikel:show_artikel' %}" style="
                background: linear-gradient(90deg, #d53369 0%, #daae51 100%);
              "
              class="mx-auto lg:mx-0 hover:underline gradient text-black font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
              Detail
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <section class="bg-gray-100 py-8">
    <div class="container mx-auto px-2 pt-4 pb-12 text-gray-800">
      <h2 class="w-full my-2 text-3xl md:text-4xl lg:text-5xl font-bold leading-tight text-center text-gray-800">
        We Provide <span class="text-red-500"> Medical </span> Services That You
        Can <span class="text-red-500"> Trust </span>!
      </h2>
      <div class="w-full mb-4">
        <div class="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
      </div>
      <div class="flex flex-col sm:flex-row justify-center pt-12 my-12 sm:my-4">
        <div class="flex flex-col w-5/6 lg:w-1/4 mx-auto lg:mx-0 rounded-none lg:rounded-l-lg bg-white mt-4">
          <div class="flex-1 bg-white text-gray-600 rounded-t rounded-b-none overflow-hidden shadow">
            <div class="p-8 text-2xl md:text-3xl lg:text-3xl font-bold text-center border-b-4">
              Konsultasi Kesehatan Anak
            </div>
            <ul class="w-full text-center text-sm"></ul>
          </div>
          <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
            <div class="w-full my-10 text-2xl text-gray-600 font-semibold text-center">
              Sering kali banyak orang tua kesulitan mengetahui konsultasi
              dokter anak yang dibutuhkan. Platform ini memudahkan orang tua
              dalam menjaga kesehatan anaknya.
            </div>
          </div>
        </div>
        <div class="flex flex-col w-5/6 lg:w-1/3 mx-auto lg:mx-0 rounded-lg bg-white mt-4 sm:-mt-6 shadow-lg z-10">
          <div class="flex-1 bg-white rounded-t rounded-b-none overflow-hidden shadow">
            <div class="w-full p-8 text-2xl md:text-3xl text-3xl font-bold text-center">
              Parenting Kesehatan Mental Anak
            </div>
            <div class="h-1 w-full gradient my-0 py-0 rounded-t"></div>
            <ul class="w-full text-center text-base font-bold"></ul>
          </div>
          <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
            <div class="w-full my-10 text-2xl font-semibold text-center">
              Terlepas banyaknya jenis pemeriksaan kesehatan tubuh untuk Si
              Kecil, ternyata kesehatan mental juga merupakan hal yang
              diutamakan, lho! Dalam konsultasi psikologi anak, perilaku anak
              akan dikaitkan dengan faktor-faktor yang diduga memengaruhi
              kemunculannya.
            </div>
          </div>
        </div>
        <div class="flex flex-col w-5/6 lg:w-1/4 mx-auto lg:mx-0 rounded-none lg:rounded-l-lg bg-white mt-4">
          <div class="flex-1 bg-white text-gray-600 rounded-t rounded-b-none overflow-hidden shadow">
            <div class="p-8 text-2xl md:text-3xl text-3xl font-bold text-center border-b-4">
              Laporan Progress Kesehatan Anak
            </div>
            <ul class="w-full text-center text-sm"></ul>
          </div>
          <div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
            <div class="w-full text-xl text-gray-600 font-bold text-center">
              Sejak tahun 2000, angka kematian anak telah berhasil diturunkan
              hampir separuhnya. Hal ini dicapai terutama melalui perbaikan
              akses pada layanan kesehatan yang terjangkau dan berkualitas.
              Melalui laporan progress, orang tua dan dokter dapat memantau
              perkembangan anak.
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Change the colour #f8fafc to match the previous section colour -->
  <svg class="wave-top" viewBox="0 0 1439 147" version="1.1" xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
      <g transform="translate(-1.000000, -14.000000)" fill-rule="nonzero">
        <g class="wave" fill="#f8fafc">
          <path
            d="M1440,84 C1383.555,64.3 1342.555,51.3 1317,45 C1259.5,30.824 1206.707,25.526 1169,22 C1129.711,18.326 1044.426,18.475 980,22 C954.25,23.409 922.25,26.742 884,32 C845.122,37.787 818.455,42.121 804,45 C776.833,50.41 728.136,61.77 713,65 C660.023,76.309 621.544,87.729 584,94 C517.525,105.104 484.525,106.438 429,108 C379.49,106.484 342.823,104.484 319,102 C278.571,97.783 231.737,88.736 205,84 C154.629,75.076 86.296,57.743 0,32 L0,0 L1440,0 L1440,84 Z">
          </path>
        </g>
        <g transform="translate(1.000000, 15.000000)" fill="#FFFFFF">
          <g transform="translate(719.500000, 68.500000) rotate(-180.000000) translate(-719.500000, -68.500000) ">
            <path
              d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496"
              opacity="0.100000001"></path>
            <path
              d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z"
              opacity="0.100000001"></path>
            <path
              d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z"
              opacity="0.200000003"></path>
          </g>
        </g>
      </g>
    </g>
  </svg>
  <section class="container mx-auto text-center py-6 mb-12">
    <h2 class="w-full my-2 text-2xl px-2 md:text-3xl text-4xl font-bold leading-tight text-center text-white">
      Check Your Child's BMI
    </h2>
    <div class="w-full mb-4">
      <div class="h-1 mx-auto bg-white w-1/6 opacity-25 my-0 py-0 rounded-t"></div>
    </div>
    <h3 class="my-10 text-2xl mx-3 lg:text-3xl leading-tight">
      A Happy Child is A Healthy Child
    </h3>
    <button
      class="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
      <a href="{% url 'bmicalculator:show_bmicalculator' %}">Check Now!</a>
    </button>


  </section>
</body>

{% endblock content %}

main/templates/register.html
{% extends "base.html" %}

{% block meta %}
<title>Kembangin | Register</title>
{% endblock meta %}

{% block content %}
<div class="text-center font-bold h-screen flex" id="content">
  <form method="POST" action="" id="register-form"
    class="grid grid-cols-1 gap-5 bg-red-200 rounded border-4 border-neutral-500 p-5 m-auto">
    {% csrf_token %}
    <div>
      <p class="text-3xl">Register Account</p>
    </div>
    <div>
      <input type="text" name="username" placeholder="Username"
        class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center" required />
    </div>
    <div>
      <input type="email" name="email" placeholder="Email"
        class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center" required />
    </div>
    <div>
      <input type="password" name="password" placeholder="Password"
        class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center" required />
    </div>
    <div>
      <input type="password" name="repeat_password"
        placeholder="Repeat password" class="form-control rounded border-2 border-black-500 hover:border-neutral-900 text-center"
        required />
    </div>
    <div>
      <p>Apakah anda dokter?</p>

      <input type="radio" id="no" name="doctor_choice" value="yes" required />
      <label for="yes">Ya</label>
      <input type="radio" id="yes" name="doctor_choice" value="no" required />
      <label for="no">Tidak</label>
    </div>
    <div>
      <button class="text-lg bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded border-2 border-neutral-500"
        type="submit">Register</button>
    </div>
    {% if messages %}
    <ul class="text-center font-bold text-black-400">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </form>
</div>
{% endblock content %}